export const NBA_PLAYERS = [
  {id:1,name:"Nikola Jokić",team:"DEN",pos:"C",tier:"Elite",adp:1.0},
  {id:2,name:"Victor Wembanyama",team:"SAS",pos:"C",tier:"Elite",adp:2.0},
  {id:3,name:"Shai Gilgeous-Alexander",team:"OKC",pos:"PG",tier:"Elite",adp:3.0},
  {id:4,name:"Luka Dončić",team:"LAL",pos:"PG",tier:"Elite",adp:4.0},
  {id:5,name:"Cade Cunningham",team:"DET",pos:"PG",tier:"Elite",adp:5.0},
  {id:6,name:"Jayson Tatum",team:"BOS",pos:"SF",tier:"Elite",adp:6.0},
  {id:7,name:"Giannis Antetokounmpo",team:"MIA",pos:"PF",tier:"Elite",adp:7.0},
  {id:8,name:"Jalen Johnson",team:"ATL",pos:"PF",tier:"Elite",adp:8.0},
  {id:9,name:"Anthony Edwards",team:"MIN",pos:"SG",tier:"Elite",adp:9.0},
  {id:10,name:"Tyrese Maxey",team:"PHI",pos:"PG",tier:"Elite",adp:10.0},
  {id:11,name:"Tyrese Haliburton",team:"IND",pos:"PG",tier:"Tier 1",adp:11.0},
  {id:12,name:"Cooper Flagg",team:"DAL",pos:"SF",tier:"Tier 1",adp:12.0},
  {id:13,name:"Scottie Barnes",team:"TOR",pos:"SF",tier:"Tier 1",adp:13.0},
  {id:14,name:"Donovan Mitchell",team:"CLE",pos:"SG",tier:"Tier 1",adp:14.0},
  {id:15,name:"Kevin Durant",team:"HOU",pos:"PF",tier:"Tier 1",adp:15.0},
  {id:16,name:"Stephen Curry",team:"GSW",pos:"PG",tier:"Tier 1",adp:16.0},
  {id:17,name:"Karl-Anthony Towns",team:"NYK",pos:"C",tier:"Tier 1",adp:17.0},
  {id:18,name:"Trae Young",team:"WAS",pos:"PG",tier:"Tier 1",adp:18.0},
  {id:19,name:"Alperen Sengun",team:"HOU",pos:"C",tier:"Tier 1",adp:19.0},
  {id:20,name:"Austin Reaves",team:"LAL",pos:"SG",tier:"Tier 1",adp:20.0},
  {id:21,name:"James Harden",team:"CLE",pos:"PG",tier:"Tier 2",adp:21.0},
  {id:22,name:"Chet Holmgren",team:"OKC",pos:"C",tier:"Tier 2",adp:22.0},
  {id:23,name:"LaMelo Ball",team:"MIN",pos:"PG",tier:"Tier 2",adp:23.0},
  {id:24,name:"Amen Thompson",team:"HOU",pos:"SF",tier:"Tier 2",adp:24.0},
  {id:25,name:"Josh Giddey",team:"CHI",pos:"PG",tier:"Tier 2",adp:25.0},
  {id:26,name:"Jamal Murray",team:"DEN",pos:"PG",tier:"Tier 2",adp:26.0},
  {id:27,name:"Anthony Davis",team:"WAS",pos:"PF",tier:"Tier 2",adp:27.0},
  {id:28,name:"Devin Booker",team:"PHX",pos:"SG",tier:"Tier 2",adp:28.0},
  {id:29,name:"Trey Murphy III",team:"NOP",pos:"SF",tier:"Tier 2",adp:29.0},
  {id:30,name:"Evan Mobley",team:"CLE",pos:"PF",tier:"Tier 2",adp:30.0},
  {id:31,name:"Jalen Brunson",team:"NYK",pos:"PG",tier:"Tier 3",adp:31.0},
  {id:32,name:"Domantas Sabonis",team:"SAC",pos:"C",tier:"Tier 3",adp:32.0},
  {id:33,name:"Lauri Markkanen",team:"UTA",pos:"PF",tier:"Tier 3",adp:33.0},
  {id:34,name:"Kawhi Leonard",team:"LAC",pos:"SF",tier:"Tier 3",adp:34.0},
  {id:35,name:"Bam Adebayo",team:"MIA",pos:"C",tier:"Tier 3",adp:35.0},
  {id:36,name:"Deni Avdija",team:"POR",pos:"SF",tier:"Tier 3",adp:36.0},
  {id:37,name:"Jalen Williams",team:"OKC",pos:"SF",tier:"Tier 3",adp:37.0},
  {id:38,name:"Brandon Miller",team:"CHA",pos:"SF",tier:"Tier 3",adp:38.0},
  {id:39,name:"Walker Kessler",team:"LAL",pos:"C",tier:"Tier 3",adp:39.0},
  {id:40,name:"Derrick White",team:"BOS",pos:"SG",tier:"Tier 3",adp:40.0},
  {id:41,name:"Jaren Jackson Jr.",team:"UTA",pos:"PF",tier:"Tier 4",adp:41.0},
  {id:42,name:"Kon Knueppel",team:"CHA",pos:"SG",tier:"Tier 4",adp:42.0},
  {id:43,name:"Jaylen Brown",team:"PHI",pos:"SF",tier:"Tier 4",adp:43.0},
  {id:44,name:"Jalen Duren",team:"DET",pos:"C",tier:"Tier 4",adp:44.0},
  {id:45,name:"Keyonte George",team:"UTA",pos:"SG",tier:"Tier 4",adp:45.0},
  {id:46,name:"Nickeil Alexander-Walker",team:"ATL",pos:"SG",tier:"Tier 4",adp:46.0},
  {id:47,name:"Darius Garland",team:"LAC",pos:"PG",tier:"Tier 4",adp:47.0},
  {id:48,name:"Kyrie Irving",team:"DAL",pos:"PG",tier:"Tier 4",adp:48.0},
  {id:49,name:"Paolo Banchero",team:"ORL",pos:"PF",tier:"Tier 4",adp:49.0},
  {id:50,name:"Desmond Bane",team:"ORL",pos:"SG",tier:"Tier 4",adp:50.0},
  {id:51,name:"Onyeka Okongwu",team:"ATL",pos:"C",tier:"Tier 5",adp:51.0},
  {id:52,name:"LeBron James",team:"PHI",pos:"SF",tier:"Tier 5",adp:52.0},
  {id:53,name:"Donovan Clingan",team:"POR",pos:"C",tier:"Tier 5",adp:53.0},
  {id:54,name:"Tyler Herro",team:"MIL",pos:"SG",tier:"Tier 5",adp:54.0},
  {id:55,name:"Matas Buzelis",team:"CHI",pos:"SF",tier:"Tier 5",adp:55.0},
  {id:56,name:"Dyson Daniels",team:"ATL",pos:"SG",tier:"Tier 5",adp:56.0},
  {id:57,name:"Franz Wagner",team:"ORL",pos:"SF",tier:"Tier 5",adp:57.0},
  {id:58,name:"Pascal Siakam",team:"IND",pos:"PF",tier:"Tier 5",adp:58.0},
  {id:59,name:"Cameron Boozer",team:"MEM",pos:"PF",tier:"Tier 5",adp:59.0},
  {id:60,name:"OG Anunoby",team:"NYK",pos:"SF",tier:"Tier 5",adp:60.0},
  {id:61,name:"Joel Embiid",team:"PHI",pos:"C",tier:"Tier 6",adp:61.0},
  {id:62,name:"Dejounte Murray",team:"NOP",pos:"PG",tier:"Tier 6",adp:62.0},
  {id:63,name:"Ryan Rollins",team:"MIL",pos:"SG",tier:"Tier 6",adp:63.0},
  {id:64,name:"Julius Randle",team:"BKN",pos:"PF",tier:"Tier 6",adp:64.0},
  {id:65,name:"Michael Porter Jr.",team:"BKN",pos:"SF",tier:"Tier 6",adp:65.0},
  {id:66,name:"Kel'el Ware",team:"MIL",pos:"C",tier:"Tier 6",adp:66.0},
  {id:67,name:"Alex Sarr",team:"WAS",pos:"C",tier:"Tier 6",adp:67.0},
  {id:68,name:"Stephon Castle",team:"SAS",pos:"PG",tier:"Tier 6",adp:68.0},
  {id:69,name:"Zach Edey",team:"MEM",pos:"C",tier:"Tier 6",adp:69.0},
  {id:70,name:"Ivica Zubac",team:"IND",pos:"C",tier:"Tier 6",adp:70.0},
  {id:71,name:"De'Aaron Fox",team:"SAS",pos:"PG",tier:"Tier 7",adp:71.0},
  {id:72,name:"Naz Reid",team:"CHA",pos:"PF",tier:"Tier 7",adp:72.0},
  {id:73,name:"Mikal Bridges",team:"NYK",pos:"SF",tier:"Tier 7",adp:73.0},
  {id:74,name:"Ja Morant",team:"POR",pos:"PG",tier:"Tier 7",adp:74.0},
  {id:75,name:"Jaden McDaniels",team:"MIN",pos:"SF",tier:"Tier 7",adp:75.0},
  {id:76,name:"Rudy Gobert",team:"MIN",pos:"C",tier:"Tier 7",adp:76.0},
  {id:77,name:"VJ Edgecombe",team:"PHI",pos:"SG",tier:"Tier 7",adp:77.0},
  {id:78,name:"Immanuel Quickley",team:"TOR",pos:"PG",tier:"Tier 7",adp:78.0},
  {id:79,name:"Coby White",team:"CHA",pos:"PG",tier:"Tier 7",adp:79.0},
  {id:80,name:"Brandon Ingram",team:"TOR",pos:"SF",tier:"Tier 7",adp:80.0},
  {id:81,name:"Paul George",team:"BOS",pos:"SF",tier:"Tier 8",adp:81.0},
  {id:82,name:"Dylan Harper",team:"SAS",pos:"SG",tier:"Tier 8",adp:82.0},
  {id:83,name:"Zion Williamson",team:"NOP",pos:"PF",tier:"Tier 8",adp:83.0},
  {id:84,name:"Jarrett Allen",team:"CLE",pos:"C",tier:"Tier 8",adp:84.0},
  {id:85,name:"Payton Pritchard",team:"BOS",pos:"PG",tier:"Tier 8",adp:85.0},
  {id:86,name:"Damian Lillard",team:"POR",pos:"PG",tier:"Tier 8",adp:86.0},
  {id:87,name:"Jalen Suggs",team:"ORL",pos:"PG",tier:"Tier 8",adp:87.0},
  {id:88,name:"Ausar Thompson",team:"DET",pos:"SF",tier:"Tier 8",adp:88.0},
  {id:89,name:"Josh Hart",team:"NYK",pos:"SF",tier:"Tier 8",adp:89.0},
  {id:90,name:"Norman Powell",team:"CHI",pos:"SG",tier:"Tier 8",adp:90.0},
  {id:91,name:"Ty Jerome",team:"MEM",pos:"PG",tier:"Tier 9",adp:91.0},
  {id:92,name:"Derik Queen",team:"NOP",pos:"C",tier:"Tier 9",adp:92.0},
  {id:93,name:"Jabari Smith Jr.",team:"HOU",pos:"PF",tier:"Tier 9",adp:93.0},
  {id:94,name:"Myles Turner",team:"MIL",pos:"C",tier:"Tier 9",adp:94.0},
  {id:95,name:"Andrew Wiggins",team:"MIA",pos:"SF",tier:"Tier 9",adp:95.0},
  {id:96,name:"AJ Dybantsa",team:"WAS",pos:"SF",tier:"Tier 9",adp:96.0},
  {id:97,name:"Nic Claxton",team:"CHI",pos:"C",tier:"Tier 9",adp:97.0},
  {id:98,name:"Isaiah Hartenstein",team:"OKC",pos:"C",tier:"Tier 9",adp:98.0},
  {id:99,name:"Day'Ron Sharpe",team:"BKN",pos:"C",tier:"Tier 9",adp:99.0},
  {id:100,name:"Caleb Wilson",team:"CHI",pos:"SF",tier:"Tier 9",adp:100.0},
  {id:101,name:"Fred VanVleet",team:"HOU",pos:"PG",tier:"Tier 10",adp:101.0},
  {id:102,name:"Darryn Peterson",team:"UTA",pos:"SG",tier:"Tier 10",adp:102.0},
  {id:103,name:"Kevin Porter Jr.",team:"MIL",pos:"SG",tier:"Tier 10",adp:103.0},
  {id:104,name:"Ayo Dosunmu",team:"MIN",pos:"SG",tier:"Tier 10",adp:104.0},
  {id:105,name:"Cedric Coward",team:"MEM",pos:"SF",tier:"Tier 10",adp:105.0},
  {id:106,name:"Kyshawn George",team:"WAS",pos:"SF",tier:"Tier 10",adp:106.0},
  {id:107,name:"CJ McCollum",team:"ATL",pos:"SG",tier:"Tier 10",adp:107.0},
  {id:108,name:"Miles Bridges",team:"PHX",pos:"PF",tier:"Tier 10",adp:108.0},
  {id:109,name:"John Collins",team:"DET",pos:"PF",tier:"Tier 10",adp:109.0},
  {id:110,name:"Ajay Mitchell",team:"OKC",pos:"PG",tier:"Tier 10",adp:110.0},
  {id:111,name:"Zach LaVine",team:"SAC",pos:"SG",tier:"Tier 11",adp:111.0},
  {id:112,name:"Keegan Murray",team:"SAC",pos:"SF",tier:"Tier 11",adp:112.0},
  {id:113,name:"Reed Sheppard",team:"HOU",pos:"SG",tier:"Tier 11",adp:113.0},
  {id:114,name:"Neemias Queta",team:"BOS",pos:"C",tier:"Tier 11",adp:114.0},
  {id:115,name:"Toumani Camara",team:"POR",pos:"SF",tier:"Tier 11",adp:115.0},
  {id:116,name:"Peyton Watson",team:"CLE",pos:"SF",tier:"Tier 11",adp:116.0},
  {id:117,name:"Collin Murray-Boyles",team:"TOR",pos:"PF",tier:"Tier 11",adp:117.0},
  {id:118,name:"Jakob Poeltl",team:"TOR",pos:"C",tier:"Tier 11",adp:118.0},
  {id:119,name:"Jalen Green",team:"PHX",pos:"SG",tier:"Tier 11",adp:119.0},
  {id:120,name:"Mark Williams",team:"PHX",pos:"C",tier:"Tier 11",adp:120.0},
  {id:121,name:"Cason Wallace",team:"OKC",pos:"SG",tier:"Tier 12",adp:121.0},
  {id:122,name:"Darius Acuff",team:"SAC",pos:"PG",tier:"Tier 12",adp:122.0},
  {id:123,name:"RJ Barrett",team:"TOR",pos:"SG",tier:"Tier 12",adp:123.0},
  {id:124,name:"Brandin Podziemski",team:"GSW",pos:"SG",tier:"Tier 12",adp:124.0},
  {id:125,name:"Jusuf Nurkić",team:"UTA",pos:"C",tier:"Tier 12",adp:125.0},
  {id:126,name:"Maxime Raynaud",team:"SAC",pos:"C",tier:"Tier 12",adp:126.0},
  {id:127,name:"Kristaps Porziņģis",team:"GSW",pos:"C",tier:"Tier 12",adp:127.0},
  {id:128,name:"Anthony Black",team:"ORL",pos:"PG",tier:"Tier 12",adp:128.0},
  {id:129,name:"Jeremiah Fears",team:"NOP",pos:"PG",tier:"Tier 12",adp:129.0},
  {id:130,name:"Sandro Mamukelashvili",team:"LAL",pos:"PF",tier:"Tier 12",adp:130.0},
  {id:131,name:"Davion Mitchell",team:"MIA",pos:"PG",tier:"Tier 13",adp:131.0},
  {id:132,name:"Egor Dëmin",team:"BKN",pos:"PG",tier:"Tier 13",adp:132.0},
  {id:133,name:"Andrew Nembhard",team:"IND",pos:"PG",tier:"Tier 13",adp:133.0},
  {id:134,name:"P.J. Washington",team:"DAL",pos:"PF",tier:"Tier 13",adp:134.0},
  {id:135,name:"Collin Gillespie",team:"PHX",pos:"PG",tier:"Tier 13",adp:135.0},
  {id:136,name:"Quentin Grimes",team:"LAL",pos:"SG",tier:"Tier 13",adp:136.0},
  {id:137,name:"Saddiq Bey",team:"NOP",pos:"SF",tier:"Tier 13",adp:137.0},
  {id:138,name:"Jaime Jaquez",team:"MIL",pos:"SF",tier:"Tier 13",adp:138.0},
  {id:139,name:"Tari Eason",team:"HOU",pos:"PF",tier:"Tier 13",adp:139.0},
  {id:140,name:"DeMar DeRozan",team:"DEN",pos:"SG",tier:"Tier 13",adp:140.0},
  {id:141,name:"Yaxel Lendeborg",team:"GSW",pos:"SF",tier:"Tier 14",adp:141.0},
  {id:142,name:"Christian Braun",team:"DEN",pos:"SG",tier:"Tier 14",adp:142.0},
  {id:143,name:"Ace Bailey",team:"UTA",pos:"SF",tier:"Tier 14",adp:143.0},
  {id:144,name:"Aaron Gordon",team:"DEN",pos:"PF",tier:"Tier 14",adp:144.0},
  {id:145,name:"Devin Vassell",team:"SAS",pos:"SG",tier:"Tier 14",adp:145.0},
  {id:146,name:"Cameron Johnson",team:"DEN",pos:"SF",tier:"Tier 14",adp:146.0},
  {id:147,name:"Bennedict Mathurin",team:"NOP",pos:"SG",tier:"Tier 14",adp:147.0},
  {id:148,name:"Jrue Holiday",team:"POR",pos:"PG",tier:"Tier 14",adp:148.0},
  {id:149,name:"Grayson Allen",team:"CHA",pos:"SG",tier:"Tier 14",adp:149.0},
  {id:150,name:"Mikel Brown Jr.",team:"BKN",pos:"PG",tier:"Tier 14",adp:150.0},
];
